const habitNameInput = document.getElementById('habit-name');
const habitDueDateInput = document.getElementById('habit-due-date');
const addHabitButton = document.getElementById('add-habit');
const habitList = document.getElementById('habit-list');

const totalHabits = document.getElementById('total-habits');
const completedHabits = document.getElementById('completed-habits');
const streaks = document.getElementById('streaks');

let habits = JSON.parse(localStorage.getItem('habits')) || [];

function saveHabits() {
    localStorage.setItem('habits', JSON.stringify(habits));
    }

    function renderHabits() {
        habitList.innerHTML = '';
            let completedTodayCount = 0;
                let currentStreak = 0;

                    habits.forEach((habit, index) => {
                            const li = document.createElement('li');
                                    li.classList.add('habit-item');
                                            
                                                    // Habit Text
                                                            const habitText = document.createElement('span');
                                                                    habitText.textContent = `${habit.name} (Due: ${habit.dueDate})`;
                                                                            if (habit.completed) {
                                                                                        habitText.style.textDecoration = 'line-through';
                                                                                                }

                                                                                                        // Mark as Complete Button
                                                                                                                const completeButton = document.createElement('button');
                                                                                                                        completeButton.textContent = habit.completed ? 'Undo' : 'Complete';
                                                                                                                                completeButton.classList.add('complete');
                                                                                                                                        completeButton.onclick = () => toggleComplete(index);

                                                                                                                                                // Delete Button
                                                                                                                                                        const deleteButton = document.createElement('button');
                                                                                                                                                                deleteButton.textContent = 'Delete';
                                                                                                                                                                        deleteButton.classList.add('delete');
                                                                                                                                                                                deleteButton.onclick = () => deleteHabit(index);

                                                                                                                                                                                        li.appendChild(habitText);
                                                                                                                                                                                                li.appendChild(completeButton);
                                                                                                                                                                                                        li.appendChild(deleteButton);
                                                                                                                                                                                                                habitList.appendChild(li);

                                                                                                                                                                                                                        // Update stats for completed habits
                                                                                                                                                                                                                                if (habit.completed) {
                                                                                                                                                                                                                                            completedTodayCount++;
                                                                                                                                                                                                                                                        currentStreak = habit.streak > currentStreak ? habit.streak : currentStreak;
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                        // Update Stats
                                                                                                                                                                                                                                                                            totalHabits.textContent = `Total Habits: ${habits.length}`;
                                                                                                                                                                                                                                                                                completedHabits.textContent = `Completed Today: ${completedTodayCount}`;
                                                                                                                                                                                                                                                                                    streaks.textContent = `Current Streak: ${currentStreak} days`;
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                    // Add new habit
                                                                                                                                                                                                                                                                                    addHabitButton.addEventListener('click', () => {
                                                                                                                                                                                                                                                                                        const habitName = habitNameInput.value.trim();
                                                                                                                                                                                                                                                                                            const habitDueDate = habitDueDateInput.value;
                                                                                                                                                                                                                                                                                                if (habitName && habitDueDate) {
                                                                                                                                                                                                                                                                                                        habits.push({ 
                                                                                                                                                                                                                                                                                                                    name: habitName, 
                                                                                                                                                                                                                                                                                                                                dueDate: habitDueDate, 
                                                                                                                                                                                                                                                                                                                                            completed: false, 
                                                                                                                                                                                                                                                                                                                                                        streak: 0 
                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                        habitNameInput.value = '';
                                                                                                                                                                                                                                                                                                                                                                                habitDueDateInput.value = '';
                                                                                                                                                                                                                                                                                                                                                                                        saveHabits();
                                                                                                                                                                                                                                                                                                                                                                                                renderHabits();
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                    // Toggle habit completion and update streak
                                                                                                                                                                                                                                                                                                                                                                                                    function toggleComplete(index) {
                                                                                                                                                                                                                                                                                                                                                                                                        const habit = habits[index];
                                                                                                                                                                                                                                                                                                                                                                                                            habit.completed = !habit.completed;
                                                                                                                                                                                                                                                                                                                                                                                                                if (habit.completed) {
                                                                                                                                                                                                                                                                                                                                                                                                                        const today = new Date().toISOString().slice(0, 10); // Get today's date
                                                                                                                                                                                                                                                                                                                                                                                                                                habit.streak = habit.lastCompleted === today ? habit.streak + 1 : 1; // Increase streak if last completed on the previous day
                                                                                                                                                                                                                                                                                                                                                                                                                                        habit.lastCompleted = today;
                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    habit.streak = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                            saveHabits();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                renderHabits();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Delete habit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                function deleteHabit(index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    habits.splice(index, 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        saveHabits();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            renderHabits();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Initial render
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            renderHabits();
